# Generated by Django 3.1.4 on 2021-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
